# Set prefix to <C-a>
unbind C-a
set -g prefix C-a
bind C-a send-prefix

# Allow scrolling to previous commands
set -g mouse on

# Shortcut for reloading this config file
bind r source-file ~/.tmux.conf

# 1 based indexing
set -g base-index 1
setw -g pane-base-index 1

# Rebind split commands
bind-key "|" split-window -hc "#{pane_current_path}"
bind-key "\\" split-window -fhc "#{pane_current_path}"
bind-key "-" split-window -vc "#{pane_current_path}"
bind-key "_" split-window -fvc "#{pane_current_path}"

# Use vim binds to swith panes
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R


