#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "$(readlink -f -- "${BASH_SOURCE[0]}")")" && pwd)"
BIN_DIR="$HOME/.local/bin"

mkdir -p "$BIN_DIR"

for f in "$SCRIPT_DIR"/*; do
  [ -f "$f" ] || continue      # Script should be a regular file
  [ -x "$f" ] || continue      # Script should be executable

  name="$(basename "$f")"
  ln -sf "$f" "$BIN_DIR/$name"
  echo "linked $BIN_DIR/$name -> $f"
done
